apiVersion: v1
kind: Endpoints
metadata:
  name: locust-data
subsets:
- addresses:
  - ip: 192.168.31.243
  ports:
  - port: 8089
    name: locust
---
apiVersion: v1
kind: Service
metadata:
  name: locust-data
  labels:
    app: locust-data
spec:
  ports:
  - port: 8089
    targetPort: 8089
    name: locust
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus
    prometheus: prometheus
  name: locust-data
spec:
  endpoints:
  - interval: 1s
    path: /export/prometheus
    targetPort: 8089
    port: locust
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: locust-data