sudo: required
dist: xenial
language: go

go:
- "1.12.x"
go_import_path: github.com/coreos/kube-prometheus

cache:
  directories:
  - $GOCACHE
  - $GOPATH/pkg/mod

services:
- docker

jobs:
  include:
  - name: Check generated files
    script: make --always-make generate-in-docker && git diff --exit-code
  - name: Run tests
    script: make --always-make test-in-docker
  - name: Run e2e tests
    script: GO111MODULE=on ./tests/e2e/travis-e2e.sh
