apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: locust-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      k8s-app: locust-master
  namespaceSelector:
    matchNames:
    - default
  podMetricsEndpoints:
  - port: loc-master-web
    path: /export/prometheus